collections:
  - provider: archidekt
    discord_user: tuckface
    provider_collection: 243732
  - provider: moxfield
    discord_user: wookiee
    provider_collection: 0LZZ8gT8DkGGeyQtG_uO1w
  - provider: moxfield
    discord_user: .sparky
    provider_collection: PUYRTn5Q2kqiBB531_1W1Q
  - provider: moxfield
    discord_user: makimakiroll
    provider_collection: b7fNJ-tWrkKN-abuIN2IgA
  - provider: moxfield
    discord_user: oberawl
    provider_collection: CdNyA-ygkEOt6ecFGHiA5A
community_decks:
  - provider: moxfield
    discord_user: oberawl
    provider_deck: ev681gZZkEOhPGQ9IqoHWQ
  - provider: moxfield
    discord_user: tuckface
    provider_deck: 6Pi0zam1Ik2BCYVJ67fKCA
  - provider: moxfield
    discord_user: .sparky
    provider_deck: PzWa0HiGREOyeGfQPU80Rg
  - provider: archidekt
    discord_user: makimakiroll
    provider_deck: 3531305