name: PR Build
on: 
  pull_request:
    types: [opened, synchronize]

permissions: write-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Configure Rust
        uses: dtolnay/rust-toolchain@1.26.0

      - name: Configure Rust Cache
        uses: Swatinem/rust-cache@v2
      
      - name: test
        run: |
          cargo test --all-features
